@echo off
echo Starting Fact Buster servers...

echo Starting backend server on port 5001...
start "Backend Server" cmd /k "cd server && npm start"

echo Waiting 3 seconds for backend to start...
timeout /t 3 /nobreak > nul

echo Starting frontend server on port 3000...
start "Frontend Server" cmd /k "cd client && npm start"

echo Both servers are starting...
echo Backend: http://localhost:5001
echo Frontend: http://localhost:3000
pause 